-- 담당자 2171028 연가은
-- 담당자 2171087 이희원

USE team14;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS match_event;
DROP TABLE IF EXISTS action_log;
DROP TABLE IF EXISTS match_team;
DROP TABLE IF EXISTS match_game;
DROP TABLE IF EXISTS player;
DROP TABLE IF EXISTS coach;
DROP TABLE IF EXISTS referee;
DROP TABLE IF EXISTS team;

SET FOREIGN_KEY_CHECKS = 1;